---
  - hosts: all
    become: True
    roles: 
      - ubuntu-security
    vars:
      ubuntu_user: user_name
      ubuntu_version: focal
      ubuntu_kernel_version: 5.4.0-77-generic   # $(uname -r)
      ubuntu_host: XXX.YYY.ZZZ.VVV    # IP Address or localhost
      ubuntu_private_key_file: ~/.ssh/demo-ssh
      ubuntu_port: 22
      ansible_python_interpreter: /usr/bin/python3